"""
SQLAlchemy ORM models for the trading system database.

Tables:
    - market_data       : Historical OHLCV price data
    - signals           : Trading signals generated by strategies
    - trades            : Executed (simulated) trades
    - portfolio         : Current portfolio holdings
    - backtest_results  : Performance metrics from backtests
    - users             : Dashboard authentication
    - auto_trade_configs: Auto-trading configuration per user
    - risk_events       : Risk management interventions log
    - watchlist         : User custom watchlist items
    - recommendations   : Smart picks history
"""

from datetime import datetime
from sqlalchemy import (
    Column, Integer, Float, String, DateTime, Date, Text,
    UniqueConstraint, Index, create_engine
)
from sqlalchemy.orm import declarative_base

Base = declarative_base()


class MarketData(Base):
    """Historical OHLCV market data."""
    __tablename__ = "market_data"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(20), nullable=False, index=True)
    date = Column(Date, nullable=False)
    open = Column(Float, nullable=False)
    high = Column(Float, nullable=False)
    low = Column(Float, nullable=False)
    close = Column(Float, nullable=False)
    volume = Column(Float, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    __table_args__ = (
        UniqueConstraint("symbol", "date", name="uq_symbol_date"),
        Index("ix_symbol_date", "symbol", "date"),
    )

    def __repr__(self):
        return f"<MarketData({self.symbol} {self.date} C={self.close})>"


class Signal(Base):
    """Trading signals generated by strategies."""
    __tablename__ = "signals"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(20), nullable=False, index=True)
    strategy_name = Column(String(50), nullable=False)
    signal_type = Column(String(10), nullable=False)  # BUY, SELL, HOLD
    price = Column(Float, nullable=False)
    confidence = Column(Float, nullable=True)  # 0.0 - 1.0
    timestamp = Column(DateTime, nullable=False, default=datetime.utcnow)
    signal_metadata = Column(Text, nullable=True)  # JSON string with extra info
    created_at = Column(DateTime, default=datetime.utcnow)

    __table_args__ = (
        Index("ix_signal_symbol_strategy", "symbol", "strategy_name"),
    )

    def __repr__(self):
        return f"<Signal({self.strategy_name} {self.signal_type} {self.symbol} @ {self.price})>"


class Trade(Base):
    """Executed (simulated) trades."""
    __tablename__ = "trades"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(20), nullable=False, index=True)
    side = Column(String(4), nullable=False)        # BUY or SELL
    quantity = Column(Float, nullable=False)
    price = Column(Float, nullable=False)
    commission = Column(Float, nullable=False, default=0.0)
    slippage = Column(Float, nullable=False, default=0.0)
    total_cost = Column(Float, nullable=False)       # price * qty + commission + slippage
    pnl = Column(Float, nullable=True)               # Realized P&L (for sells)
    strategy_name = Column(String(50), nullable=False)
    timestamp = Column(DateTime, nullable=False, default=datetime.utcnow)
    created_at = Column(DateTime, default=datetime.utcnow)

    def __repr__(self):
        return f"<Trade({self.side} {self.quantity} {self.symbol} @ {self.price})>"


class Portfolio(Base):
    """Current portfolio holdings snapshot."""
    __tablename__ = "portfolio"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(20), nullable=False, unique=True)
    quantity = Column(Float, nullable=False, default=0.0)
    avg_cost = Column(Float, nullable=False, default=0.0)
    current_price = Column(Float, nullable=True)
    current_value = Column(Float, nullable=True)
    unrealized_pnl = Column(Float, nullable=True)
    last_updated = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    def __repr__(self):
        return f"<Portfolio({self.symbol} qty={self.quantity} avg={self.avg_cost})>"


class BacktestResult(Base):
    """Results from backtesting a strategy."""
    __tablename__ = "backtest_results"

    id = Column(Integer, primary_key=True, autoincrement=True)
    strategy_name = Column(String(50), nullable=False)
    symbol = Column(String(20), nullable=False)
    start_date = Column(Date, nullable=False)
    end_date = Column(Date, nullable=False)
    initial_capital = Column(Float, nullable=False)
    final_value = Column(Float, nullable=False)
    total_return_pct = Column(Float, nullable=False)
    sharpe_ratio = Column(Float, nullable=True)
    max_drawdown_pct = Column(Float, nullable=True)
    win_rate = Column(Float, nullable=True)
    total_trades = Column(Integer, nullable=False)
    winning_trades = Column(Integer, nullable=True)
    losing_trades = Column(Integer, nullable=True)
    avg_trade_pnl = Column(Float, nullable=True)
    equity_curve = Column(Text, nullable=True)  # JSON serialized list
    created_at = Column(DateTime, default=datetime.utcnow)

    def __repr__(self):
        return (
            f"<BacktestResult({self.strategy_name} {self.symbol} "
            f"return={self.total_return_pct:.2f}%)>"
        )


class User(Base):
    """User accounts for dashboard authentication."""
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, autoincrement=True)
    username = Column(String(50), nullable=False, unique=True)
    email = Column(String(120), nullable=False, unique=True)
    password_hash = Column(String(256), nullable=False)
    full_name = Column(String(100), nullable=True)
    session_token = Column(String(128), nullable=True, index=True)
    session_expiry = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    last_login = Column(DateTime, nullable=True)

    def __repr__(self):
        return f"<User({self.username})>"


class AutoTradeConfig(Base):
    """Auto-trading configuration per user."""
    __tablename__ = "auto_trade_configs"

    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(Integer, nullable=False, index=True)
    is_active = Column(Integer, default=0)          # 0=off, 1=on
    strategy_name = Column(String(50), nullable=False, default="sma")
    symbols = Column(Text, nullable=False)           # JSON list of symbols
    interval_minutes = Column(Integer, default=15)
    max_position_pct = Column(Float, default=0.2)    # Max % of capital per position
    stop_loss_pct = Column(Float, nullable=True)
    take_profit_pct = Column(Float, nullable=True)
    market_hours_only = Column(Integer, default=1)   # 0=no, 1=yes
    last_run = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    def __repr__(self):
        return f"<AutoTradeConfig(user={self.user_id} active={self.is_active})>"


class RiskEvent(Base):
    """Risk management intervention log."""
    __tablename__ = "risk_events"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(20), nullable=False, index=True)
    event_type = Column(String(30), nullable=False)  # STOP_LOSS, TRAILING_STOP, TAKE_PROFIT, etc.
    severity = Column(String(10), nullable=False, default="info")  # info, warning, danger
    message = Column(Text, nullable=False)
    action_taken = Column(String(100), nullable=True)
    price_at_event = Column(Float, nullable=True)
    pnl_at_event = Column(Float, nullable=True)
    timestamp = Column(DateTime, nullable=False, default=datetime.utcnow)
    created_at = Column(DateTime, default=datetime.utcnow)

    def __repr__(self):
        return f"<RiskEvent({self.event_type} {self.symbol} {self.severity})>"


class Watchlist(Base):
    """User custom watchlist items."""
    __tablename__ = "watchlist"

    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(Integer, nullable=False, index=True)
    symbol = Column(String(20), nullable=False)
    added_at = Column(DateTime, default=datetime.utcnow)
    notes = Column(Text, nullable=True)

    __table_args__ = (
        UniqueConstraint("user_id", "symbol", name="uq_user_symbol"),
    )

    def __repr__(self):
        return f"<Watchlist(user={self.user_id} {self.symbol})>"


class Recommendation(Base):
    """Smart picks / recommendations history."""
    __tablename__ = "recommendations"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(20), nullable=False, index=True)
    signal_type = Column(String(15), nullable=False)  # Strong Buy, Buy, Hold, Sell, Strong Sell
    confidence = Column(Float, nullable=False, default=0.0)
    reason = Column(Text, nullable=True)
    strategy_name = Column(String(50), nullable=True)
    price_at_signal = Column(Float, nullable=True)
    risk_level = Column(String(10), nullable=True)  # low, medium, high
    timestamp = Column(DateTime, nullable=False, default=datetime.utcnow)
    created_at = Column(DateTime, default=datetime.utcnow)

    def __repr__(self):
        return f"<Recommendation({self.signal_type} {self.symbol} conf={self.confidence}%)>"


class BrokerState(Base):
    """Persisted broker state — survives browser refresh and close."""
    __tablename__ = "broker_state"

    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(Integer, nullable=False, index=True)
    broker_type = Column(String(20), nullable=False, default="paper")  # paper | zerodha | angel
    is_connected = Column(Integer, default=0)
    cash = Column(Float, default=100000.0)
    initial_capital = Column(Float, default=100000.0)
    positions_json = Column(Text, nullable=True)   # JSON: {symbol: {quantity, avg_cost, current_price}}
    orders_json = Column(Text, nullable=True)       # JSON serialized recent orders
    daily_pnl = Column(Float, default=0.0)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    def __repr__(self):
        return f"<BrokerState(user={self.user_id} type={self.broker_type} connected={self.is_connected})>"
